### ISSUE TITLE
distro detection not functional on distros that support other package managers

### ISSUE THREAD

**Issue by Jan200101** [ethteck/papermario#115]
distros that provide the ability to install multiple package managers (Fedora) or mix various distros together (Bedrock) will have some trouble with the install script

**Comment by ethteck** [comment]
Thanks for raising this. Yeah, we should probably use uname or something to detect the distro rather than checking for package managers to be installed.

**Comment by nanaian** [comment]
Although this is a valid point, I feel like any users that run Bedrock or install something other than DNF on Fedora will have the technical knowledge to be able to figure out which dependencies to install themselves.

**Comment by ethteck** [comment]
Yeah, personally I think the fact that we even have an install script is a luxury, so while I do think this can be improved, it's low priority imo. @Jan200101 if you need help setting up, though, reach out and we'll be happy to assist.

**Comment by ethteck** [comment]
@Jan200101 a fix has been merged in, so I'm closing this. Let us know if you have any questions.
