### ISSUE TITLE
Type naming

### ISSUE THREAD

**Issue by nanaian** [ethteck/papermario#20]
Continuing from [this note](https://github.com/ethteck/papermario/pull/18#discussion_r471016481), it looks like a number of us would prefer that we use `CamelCase` for types (although, I assume, value types like `s32` can stay as they are from ultra64.h). 
Currently we mostly(!) use `snake_case`, following Star Rod's lead, even though SR is also inconsistent in places.

It might be worth considering how we currently name enums, too - the `SCREAMING_CAPS` for enum _members_ - as they're constants - is fine, in my opinion, but the actual enum _type_ is less awesome. Similarly, the current discrepancy between the type `npc` (`struct npc`) and the enum type `NPC` (which is a union between npc* and some special values) is a bit awkward.

**Comment by nanaian** [comment]
For enums we could have their type be `CamelCase` - just like struct types - but for the members use `MyEnum_MY_MEMBER`?

**Comment by ethteck** [comment]
I like all these ideas. :)

**Comment by ethteck** [comment]
yeah I'm not sure about npc vs NPC. I think maybe NpcId_ for the enum?

**Comment by nanaian** [comment]
Maybe `NpcRef` for the enum since 'reference' suggests pointer or id

**Comment by nanaian** [comment]
From discussion on Discord:

- `Npc` - struct
- `NpcId` - typedef for npc id
- `NpcId_SELF` - npc id value
- Don't capitalise acronyms like NPC or ID in type or variable names
